print("TEST PSYCHOLOGICZNY - CZY LUBISZ SZKOŁĘ? 😎\n")
print("Czy lubisz szkołę?\n")
print("odpowiedź A: TAK")
print("odpowiedź B: NIE\n")
zmienna = input("Podaj odpowiedź A/B: ")
print("\n******************************")
print("WYNIK TESTU:")
print("Jeśli podałeś odpowiedź 'A' - lubisz szkołę.")
print("Jeśli wybrałeś odpowiedź 'B' - nie lubisz szkoły.")
